### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/CRiSp#29]
In `get_osm_city_boundary`, from `R/retreive-osm.R`:

```
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `"name:en"` instead of `.data$name:en`
```

and:

```
Use of .data in tidyselect expressions was deprecated in tidyselect 1.2.0.
i Please use `"name"` instead of `.data$name`
```

**Comment by cforgaci** [comment]
This is not an issue. The message we get refers to the `.data` pronoun from the `tidyselect` package, whereas we are importing the `rlang::.data` pronoun which is something different.
