### ISSUE TITLE
Add DEM module

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/CRiSp#35]
We should include a module to handle DEM data. I don't expect this to be too large, so we might go for one module handling retrieval and processing, if this will grow in future we might think about splitting the two tasks in dedicated modules.

Reference material for implementation: https://github.com/CityRiverSpaces/prototyping/tree/main/notebooks/river-valley

**Comment by fnattino** [comment]
Hey @meiertgrootes, I have discussed with @cforgaci  the naming and API of CRiSP. I think this should not affect the work here, maybe add all functionalities related to the DEM in a module `R/valley.R`?

**Comment by meiertgrootes** [comment]
Sure makes sense. working on it
