### ISSUE TITLE
Add corridor segmentation module 

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/CRiSp#37]
Dependent on https://github.com/CityRiverSpaces/rcoins/issues/5 

Once we can grow strokes from specific edges in `rcoins`, we should be able to implement the river corridor segmentation in R (see reference in Python: https://github.com/CityRiverSpaces/prototyping/blob/main/notebooks/segments/segments_bucharest_river-valley.ipynb).

**Comment by cforgaci** [comment]
Consider #20 too when addressing this issue
