### ISSUE TITLE
Add DEM to packaged data

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/CRiSp#49]
Once #42 is merged, we should add the DEM for the AoI to the packaged data (as also needed by tests - see #48)

**Comment by cforgaci** [comment]
#42 closed now. The use of the DEM should also be updated in the [delineation vignette](https://github.com/CityRiverSpaces/CRiSp/blob/c663aa32346c2a0ef51b9a06d066afda79dc993f/vignettes/corridor-delineation.Rmd#L48) and we should add `method = "dem"` to [`initial_corridor()`](https://github.com/CityRiverSpaces/CRiSp/blob/c663aa32346c2a0ef51b9a06d066afda79dc993f/R/corridor.R#L62-L71).
